name = "back"
compatibility_date = "2024-08-12"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDQxZmRmMmItYmU1Mi00ZGFhLTk5MDUtZmY2YzZkZTk2MjkzIiwidGVuYW50X2lkIjoiY2U4OTZjYWI1ZmFiMDQ2YWEzYjI4OWQyMTQ3NDNjNDk5ZjdlMGRiY2E5NGI2NjU0ODM5MjdmNjEzMDQ0NWFhZCIsImludGVybmFsX3NlY3JldCI6ImU5OTY2Y2NlLWU0YzctNDIwMy1iMjRhLTEyNGY2NzdjMjRkMyJ9.9sPwhU1Gdb4hQJ6ZK68uzOBqk04hZz1wo4vnEPGmS18"